/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cathering;

import com.placeholder.PlaceHolder;
import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;

/**
 *
 * @author asus
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    PlaceHolder holder;
    DefaultTableModel laporan;
    public laporan() {
        initComponents();
        setLocationRelativeTo(this);
        holder = new PlaceHolder(jTextField1,"Cari ID Pelanggan..");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        String []judul={"NO","ID PELANGGAN","NAMA PELANGGAN","ALAMAT PELANGGAN","NO TLP",
            "TANGGAL PENGIRIMAN","PAKET PESANAN","JUMLAH PESANAN","TOTAL HARGA","DIBAYAR","SISA PEMBAYARAN","STATUS"};
        laporan = new DefaultTableModel(judul,0);
        jTable1.setModel(laporan);
        TableColumn column;
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTable1.getColumnModel().getColumn(0); 
        column.setPreferredWidth(30);
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(60);
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(250);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(120);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(150);
        column = jTable1.getColumnModel().getColumn(6); 
        column.setPreferredWidth(600);
        column = jTable1.getColumnModel().getColumn(7); 
        column.setPreferredWidth(120);
        column = jTable1.getColumnModel().getColumn(8); 
        column.setPreferredWidth(120);
        column = jTable1.getColumnModel().getColumn(9); 
        column.setPreferredWidth(120);
        column = jTable1.getColumnModel().getColumn(10); 
        column.setPreferredWidth(120);
        column = jTable1.getColumnModel().getColumn(11); 
        column.setPreferredWidth(120);
        //FUNGSI PENDUKUNG
        tampilkanlaporan();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laporan - Katering Barokah");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 204));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("EXP PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("EXP EXCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton3.setText("CARI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN KATERING BAROKAH");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Lunas", "Belum Lunas" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produk-Makanan");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pelunasan");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // HOME
        this.setVisible(false);
        this.dispose();
        home frame = new home();
        frame.setDefaultCloseOperation( EXIT_ON_CLOSE );
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // PRODUK_MAKANAN
        produk frame = new produk();
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // PELUNASAN
        pelunasan frame = new pelunasan();
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // LAPORAN
        this.setVisible(false);
        this.dispose();
        laporan frame = new laporan();
        frame.setDefaultCloseOperation( EXIT_ON_CLOSE );
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // KONFIRMASI KELUAR
        String ObjButtons[] = {"Ya","Tidak"};

        int PromptResult = JOptionPane.showOptionDialog(null,
        "Anda Yakin Ingin Keluar ?", "Peringatan",
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
        ObjButtons,ObjButtons[1]);
        if(PromptResult==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TAMPILKAN LAPORAN BERDASARKAN KONDISI STATUS KEY PRESSED
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            int row = jTable1.getRowCount();
            int row_i =1;
            for(int s=0;s<row;s++)
            {
                laporan.removeRow(0);
            }          
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cathering","root","");
            ResultSet rs = koneksi.createStatement().executeQuery("select *from pelanggan natural join pemesanan where status = '"+jComboBox1.getSelectedItem()+"' ");
            while(rs.next())
            {
                String barang[]={""+row_i++,rs.getString("id_pelanggan"),rs.getString("nama_pelanggan"),rs.getString("alamat_pelanggan"),
                    rs.getString("no_tlp"),rs.getString("tanggal_pengiriman"),rs.getString("paket_pesanan"),rs.getString("jumlah_pesanan"),
                rs.getString("total_harga"),rs.getString("dibayar"),rs.getString("sisa_pembayaran"),rs.getString("status")};
                laporan.addRow(barang);
            }
        } catch (SQLException ex) {
            Logger.getLogger(produk.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // REFRESH
        tampilkanlaporan();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // PENCARIAN
        pencarian();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // PENCARIAN KEY PRESSED
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            pencarian();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // EKSPOR TO EXCEL
        toExcel(jTable1, new File("Laporan Barokah Cathering.xls"));
        JOptionPane.showMessageDialog(null, "Laporan Berhasil Dicetak");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // EKSPOR TO PDF
            String NamaFile = "src/cathering/struk_pemesanan.jasper";
            
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cathering","root","");
            HashMap param = new HashMap();
            param.put("id_pelanggan", jTextField1.getText());
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint, false);
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // CETAK PDF MOUSE CLICK
        int i = jTable1.getSelectedRow();
        if(i>-1)
        {
            jTextField1.setText(laporan.getValueAt(i, 1).toString());
        }
        try {
            // EKSPOR TO PDF
            String NamaFile = "src/cathering/struk_pemesanan.jasper";
            
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cathering","root","");
            HashMap param = new HashMap();
            param.put("id_pelanggan", jTextField1.getText());
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint, false);
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void tampilkanlaporan(){
    try {
            int row = jTable1.getRowCount();
            int row_i =1;
            for(int s=0;s<row;s++)
            {
                laporan.removeRow(0);
            }          
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cathering","root","");
            ResultSet rs = koneksi.createStatement().executeQuery("select *from pelanggan natural join pemesanan");
            while(rs.next())
            {
                String barang[]={""+row_i++,rs.getString("id_pelanggan"),rs.getString("nama_pelanggan"),rs.getString("alamat_pelanggan"),
                    rs.getString("no_tlp"),rs.getString("tanggal_pengiriman"),rs.getString("paket_pesanan"),rs.getString("jumlah_pesanan"),
                rs.getString("total_harga"),rs.getString("dibayar"),rs.getString("sisa_pembayaran"),rs.getString("status")};
                laporan.addRow(barang);
            }
        } catch (SQLException ex) {
            Logger.getLogger(produk.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void pencarian(){
    try {
            int row = jTable1.getRowCount();
            int row_i =1;
            for(int s=0;s<row;s++)
            {
                laporan.removeRow(0);
            }          
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cathering","root","");
            ResultSet rs = koneksi.createStatement().executeQuery("select *from pelanggan natural join pemesanan where id_pelanggan LIKE '"+"%"+jTextField1.getText()+"%"+"' OR nama_pelanggan LIKE '"+"%"+jTextField1.getText()+"%"+"' ");
            while(rs.next())
            {
                String barang[]={""+row_i++,rs.getString("id_pelanggan"),rs.getString("nama_pelanggan"),rs.getString("alamat_pelanggan"),
                    rs.getString("no_tlp"),rs.getString("tanggal_pengiriman"),rs.getString("paket_pesanan"),rs.getString("jumlah_pesanan"),
                rs.getString("total_harga"),rs.getString("dibayar"),rs.getString("sisa_pembayaran"),rs.getString("status")};
                laporan.addRow(barang);
            }
        } catch (SQLException ex) {
            Logger.getLogger(produk.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void toExcel(JTable jTable1,File file){
        FileWriter excel = null;
        try {
            TableModel model = jTable1.getModel();
            excel = new FileWriter(file);
            for(int x=0;x<model.getColumnCount();x++){
                excel.write(model.getColumnName(x)+"\t");
            }   excel.write("\n");
            for(int x=0;x<model.getRowCount();x++){
                for(int y=0;y<model.getColumnCount();y++){
                    excel.write(model.getValueAt(x,y).toString()+"\t");
                }
                excel.write("\n");
            }   excel.close();
        } catch (IOException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                excel.close();
            } catch (IOException ex) {
                Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
}
}
